### ISSUE TITLE
APK PLEASE !

### ISSUE THREAD

**Issue by ghost** [qandeelabbassi/touch-block#1]
WHY NO DAMN APK IN RELEASES ?!

**Comment by qandeelabbassi** [comment]
@100doses [here's the DAMN apk](https://github.com/qandeelabbassi/touch-block/tree/master/app/release) :p

**Comment by qandeelabbassi** [comment]
I haven't tested it on the later versions of Android so I am not sure if it would work. The latest version I tested it on was Lollipop or Nougat I guess

**Comment by ghost** [comment]
> @100doses [here's the DAMN apk](https://github.com/qandeelabbassi/touch-block/tree/master/app/release) :p

Thx ^^
Because almost every GitHub project has not APK and they not planned to release one.
I'm tired of compiling error due to Gradle depends which was hosted on a dead repo. :x
